### ISSUE TITLE
具体的操作

### ISSUE THREAD

**Issue by systemime** [HunterXuan/WebQATest#1]
博主可以说明一下修改 service.py 内的模型载入路径后，具体的操作步骤么，感谢

**Comment by HunterXuan** [comment]
1. 运行 `python gen.py`
2. 运行 `python insqa_cnn.py` 模型训练
3. 根据训练时模型的保存路径，修改 [路径](https://github.com/HunterXuan/WebQATest/blob/master/service.py#L89)
4. 运行 `python`，进入交互模式，然后 `imoprt service`，`service.print_random_qa()`，`service.get_top_answers('杨利伟是谁？')`

**Comment by HunterXuan** [comment]
#2

**Comment by systemime** [comment]
我正确训练模型以后，再次运行，为什么可能的答案与问题一个都没关系，比如实例中“杨利伟是谁”，出来的答案是武媚娘是谁之类，，，训练的模型最后稳定再0.75上下
