### ISSUE TITLE
模型答案准确性

### ISSUE THREAD

**Issue by systemime** [HunterXuan/WebQATest#3]
我正确训练模型以后，再次运行，为什么可能的答案与问题一个都没关系，比如实例中“杨利伟是谁”，出来的答案是武媚娘是谁之类，，，训练的模型最后稳定再0.75上下

**Comment by HunterXuan** [comment]
嗯，这边上传的代码是比较旧的，实际测试效果一般。
实际业务中我们使用的是问题对的匹配，而且用的是比较干净的语料，效果会好点。
有兴趣的话，你可以尝试改下，或者尝试下其它模型，比如 ESIM 或者 BERT。

**Comment by systemime** [comment]
谢谢，我回头去试试，
