### ISSUE TITLE
data文件的具体功能

### ISSUE THREAD

**Issue by systemime** [HunterXuan/WebQATest#4]
data文件中的json、txt以及model，它们的作用是什么，博主可以说明一下吗？感谢

**Comment by HunterXuan** [comment]
corpus.txt 是用来生成词向量的，词向量的 model 就是 word2vec.model
webqa.json 是WebQA 的数据集，用于生成训练数据集 train.json

**Comment by systemime** [comment]
我基于我的文本生成了词向量后，修改webqa.json中的内容，在训练模型时循环出现
`setting an array element with a sequence.`
请问这种情况博主遇到过吗？

**Comment by HunterXuan** [comment]
> 我基于我的文本生成了词向量后，修改webqa.json中的内容，在训练模型时循环出现
> `setting an array element with a sequence.`
> 请问这种情况博主遇到过吗？

表示没有遇到过这种情况
